name: scheduleRenderbook
on:     
  push:
  schedule:     
     - cron: "0 3 * * *"  

jobs:
  import-data:
    name: Render-Map
    runs-on:   macos-latest # ubuntu-latest #  macos USES 10 TIMES THE MINUTES
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      # More detail here, https://github.com/r-lib/actions
      # It's possible to define R and pandoc version if desired
      - uses: r-lib/actions/setup-r@v2
        
#      - name: Install rgdal
#        run: Rscript -e "install.packages('rgdal', type='mac.binary')"  
      - name: Install units
        run: Rscript -e "install.packages('units')"
      - name: Install leaflet
        run: Rscript -e "install.packages('leaflet')"
      - name: Install move
        run: Rscript -e "install.packages('move')"
      - name: Install dplyr
        run: Rscript -e "install.packages('dplyr')"
      - name: Install sf
        run: Rscript -e "install.packages('sf')"
      - name: Install viridis
        run: Rscript -e "install.packages('viridis')"
      - name: Install kableExtra
        run: Rscript -e "install.packages('kableExtra')"
      - name: Install lubridate
        run: Rscript -e "install.packages('lubridate')"
      - name: Install raster
        run: Rscript -e "install.packages('raster', type='mac.binary')"
      - name: Install googledrive
        run: Rscript -e "install.packages('googledrive')"
      - name: Install purrr
        run: Rscript -e "install.packages('purrr')"
      - name: Install readxl
        run: Rscript -e "install.packages('readxl')"
      - name: Install geosphere
        run: Rscript -e "install.packages('geosphere')"
      - name: Install foreach
        run: Rscript -e "install.packages('foreach')"
      - name: Install leaflet.opacity
        run: Rscript -e "install.packages('leaflet.opacity')"
      - name: Install leaflet.opacity
        run: Rscript -e "install.packages('leaflet.extras')"
      - name: Install leaflet.extras
        run: Rscript -e "install.packages('htmlwidgets')"
      - name: Render Map
        env: 
          GOOGLE_AUTHENTICATION_CREDENTIALS: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS }}
          MOVEBANK_USERNAME: ${{ secrets.MOVEBANK_USERNAME }}
          MOVEBANK_PASSWORD: ${{ secrets.MOVEBANK_PASSWORD }}
        run: Rscript -e 'source("make_leaflet.R")'
       
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit -m 'Map updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        
        
        
        
 